name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CCACHE_ACTION_CI: true

jobs:
  build:
    # Run npm build and check that the dist/ folder is up to date.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          git diff --exit-code

  test_ccache:
    # Test that ccache is installed and configured correctly.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        shell: [bash]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run ccache-action
        id: ccache
        uses: ./
        with:
          verbose: 2
          max-size: 10M
          key: parent
      - name: Test ccache 1/2
        run: |
          [[ ${{ steps.ccache.outputs.test-cache-hit }} = true ]] || [[ ${{ steps.ccache.outputs.test-cache-hit }} = false ]]
          which ccache
          ccache -V
          # Some versions of ccache don't have -v or -s
          ccache -sv || ccache -s || true
          # Example program
          echo "int x = $RANDOM;" > test.c
          ccache gcc test.c -c -o test.o
      - name: Re-compile test program in Bash
        run: ccache gcc test.c -c -o test.o
      - name: Re-compile test program in Bash
        run: ccache gcc test.c -c -o test.o
        if: ${{ matrix.shell == 'bash' }}
      - name: Test ccache 2/2
        run: |
          ccache -sv || ccache -s || true
          ccache -s | grep -E '(Hits:.+2.+/.+3)|cache hit.+2$|Cache hits.+2$'
        if: ${{ !matrix.xfail }}

  test_cache_hit:
    # Test that loading from the cache works.
    needs: [test_ccache]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        shell: [bash]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run ccache action
        uses: ./
        id: output
        with:
          key: parent
      - name: Test output true
        run: |
          [[ ${{ steps.output.outputs.test-cache-hit }} = true ]]

  test_cache_miss:
    # Test that cache misses do not break anything.
    needs: [test_ccache]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        shell: [bash]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "RAND=$RANDOM" >> $GITHUB_ENV
      - name: Run ccache action
        uses: ./
        id: output
        with:
          key: random-key-${{ env.RAND }}
      - name: Test output false
        run: |
          [[ ${{ steps.output.outputs.test-cache-hit }} = false ]]

  test_restore_keys:
    # Test the "restore-keys" option.
    needs: [test_ccache]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        shell: [bash]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "RAND=$RANDOM" >> $GITHUB_ENV
      - name: Run ccache action
        uses: ./
        id: restore-keys
        with:
          key: child-${{ env.RAND }}
          restore-keys: |
            parent
      - name: Test restore-keys
        run: |
          [[ ${{ steps.restore-keys.outputs.test-cache-hit }} = true ]]

  test_docker:
    # Test that it works in a Docker container without sudo.
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt update
        shell: bash
      - name: Run ccache-action
        uses: ./

  test_option_save:
    # Test that the 'save' option is available.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        save: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Run ccache-action
        uses: ./
        with:
          save: ${{ matrix.save }}
